//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Data.Entity.Infrastructure;

namespace CT3Application.Web.Data
{
    using System.Data.Entity;

    public partial class ApplicationDbContext : DbContext
    {
        //public ApplicationDbContext()
        //    : base("name=ApplicationDbContext")
        //{
        //}

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public virtual DbSet<C__migrationhistory> C__migrationhistory { get; set; }
        public virtual DbSet<task> tasks { get; set; }
    }
}
