//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CT3Application.Web.Data
{
    public partial class task
    {
        public System.Guid Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
    }
}
